window.onload = function () {
    // get initial content
    var hint = document.getElementById('hint');
    var content = document.getElementById('game');
    fetch(
        get_api_url(),
        {
            method: "GET",
            credentials: "same-origin",
            cache: "no-cache",
        }
    ).then(function (response) {
        if (!response.ok) {
            content.innerText = "A network error occurred. This message is not from a batch file";
            return;
        }
        response.json().then(function (data) {
            if (data["bat"] !== null) {
                content.innerText = data["html"];
                hint.innerHTML = create_hint_text(data['bat']);
            }
        }).catch(function () {
            content.innerText = "The API returned broken JSON data. This message is not from a batch file";
        });
    });

    // auto-focus input text field
    var input = document.getElementById('user_input');
    input.focus();
    input.select();

    // attach listener for Enter key
    input.addEventListener("keyup", function (event) {
        // Number 13 is the "Enter" key on the keyboard
        if (event.keyCode === 13) {
            document.getElementById("submit").click();
        }
    });
}

function quit() {
    fetch(
        `${get_api_url()}quit`,
        {
            method: "GET",
            credentials: "same-origin",
            cache: "no-cache",
        }
    ).then(function () {
        window.location.replace(`${window.location}`);
    });
}

function update() {
    var hint = document.getElementById('hint');
    var content = document.getElementById('game');
    var input = document.getElementById('user_input');
    fetch(
        `${get_api_url()}input`,
        {
            method: "POST",
            credentials: "same-origin",
            cache: "no-cache",
            body: JSON.stringify(input.value),
            headers: new Headers({
                "content-type": "application/json",
            })
        }
    ).then(function (response) {
        if (input.value == "quit") { quit() }
        input.value = "";
        response.json().then(function (data) {
            if (data["bat"] !== null) {
                content.innerText = data["html"];
                hint.innerHTML = create_hint_text(data['bat']);
            }
        });
    });
}

function create_hint_text(bat) {
    return `generated by <a href="https://github.com/tassaron/batchfile.py/blob/main/games/funtimes/${bat}">${bat}</a>, a batch file written in 2008`;
}

function get_api_url() {
    return `${window.location}/api/`
}
